services:
  supervisor-bot:
    build: .
    container_name: supervisor-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
    volumes:
      - ./data:/app/data
    env_file:
      - .env
